CRISPY_TEMPLATE_PACK = "bootstrap3"

# django-storages
S3DIRECT_REGION = 'us-west-2'
AWS_ACCESS_KEY_ID = 'AKIAJ5GFRK4K3NNL5SFQ'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'mr-upload'
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
MEDIAFILES_LOCATION = 'media'
MEDIA_URL = 'https://%s/%s/' % (AWS_S3_CUSTOM_DOMAIN, MEDIAFILES_LOCATION)
MEDIA_ROOT = MEDIA_URL
AWS_QUERYSTRING_AUTH = True
AWS_DEFAULT_ACL = 'private'
AWS_FILE_EXPIRE = 200
